### ISSUE TITLE
Help: How to send Client Certificate for Client Authentication

### ISSUE THREAD

**Issue by ghost** [tls-attacker/TLS-Attacker#95] opened 2021-04-12 08:21 UTC
I am trying to send client certificate so that s_server can authenticate the client. 
How can I send self signed certificates using tls_attacker?

**Comment by ic0ns** [comment] 2021-04-12 08:28
You have multiple possibilities to do this. You can either create a custom workflow trace where you add the Certificate and CertificateVerify messages manually, or enable clientAuthentication in the Config to automatically add the messages. If you want to do this with the example Client you can do this like this: You can choose the certificate you send with the -cert and -key flags.
config.xml:
```
<config>
    <clientAuthentication>true</clientAuthentication>
</config>

```
Then you can start the client:`
java -jar TLS-Client.jar -connect localhost:4433 -config config.xml`

**Comment by skommula96** [comment] 2021-04-12 08:33
I am using WorkflowTraceType.FULL. How can I add certificate and key  to that workflow trace?  Or if I need to create a custom workflow trace can you guide me how to?

**Comment by ic0ns** [comment] 2021-04-12 08:36
if you load up the config I posted they get added automatically to the WorkflowTrace. If you are using code you can use:
`config.setClientAuthentication(true);`

**Comment by skommula96** [comment] 2021-04-12 09:55
I want to run this command in loop using different keys and certs <openssl s_client -connect localhost:4433 -msg -cert client.crt -key client.key>. How can I replicate this in tlsattacker?
So, I am setting the **setAutoSelectCertificate(false)** and to parse the certificate.pem and key.pem which has been created using openssl.
The issue is, that I do not know how to parse these files using tlsattacker.

**Comment by ic0ns** [comment] 2021-04-12 11:08
We have a small Helper class for that called PemUtil:
```
Certificate readCertificate = PemUtil.readCertificate(new FileInputStream(new File("cert.pem")));
PrivateKey privateKey = PemUtil.readPrivateKey(new FileInputStream(new File("key.pem")));
config.setDefaultExplicitCertificateKeyPair(new CertificateKeyPair(readCertificate, privateKey));
```

**Comment by skommula96** [comment] 2021-04-12 12:02
Working as expected 
Thanks for your support @ic0ns

**Comment by skommula96** [comment] 2021-04-12 15:50
**client side:** 

 tls13Init.setClientAuthentication(true);
tls13Init.setClientAutoSelectCertificate(false);
Certificate readCertificate = PemUtil.readCertificate(new FileInputStream(new File("src/main/resources/rsa1024.cert")));
PrivateKey privateKey = PemUtil.readPrivateKey(new FileInputStream(new File("src/main/resources/rsa2048.key")));
tls13Init.setClientDefaultExplicitCertificateKeyPair(new CertificateKeyPair(readCertificate, privateKey));
State state = TLS13Execute.execute(tls13Init.getConf(), classWorkflowTraceType, alert);
AssertionCheck.checkHandshakeMessages(state);

**Server side:**

```
openssl s_server -key server.key -cert server.crt -msg -Verify 1
```


```
<<< ??? [length 0005]
    16 03 03 03 45
<<< TLS 1.3, Handshake [length 0345], ClientHello
    01 00 03 41 03 03 c6 be f9 e9 60 b4 20 bb 38 51
    d9 d4 7a cb 93 3d be 70 39 9b f6 c9 2d a3 3a f0
    1d 4f b7 70 e9 8c 00 02 8e 00 0a 00 2f 00 01 00
    02 00 3c 00 3d 00 35 00 41 00 84 00 07 00 09 00
    96 00 04 00 05 c0 9c c0 9d 00 9c 00 9d 00 0d 00
    10 00 13 00 16 00 17 00 19 00 18 00 1a 00 1b 00
    30 00 31 00 32 00 33 00 34 00 36 00 37 00 38 00
    39 00 3a c0 03 c0 04 c0 05 c0 08 c0 09 c0 0a c0
    0d c0 0e c0 0f c0 12 c0 13 c0 14 c0 27 c0 24 c0
    28 00 a1 00 a0 00 a5 00 a6 00 a7 00 9e 00 9f 00
    67 00 6b 00 6c 00 6d 00 15 c0 9e c0 9f 00 9a 00
    45 00 88 00 a2 00 a3 00 66 c0 31 c0 32 c0 11 c0
    2f c0 30 c0 2d c0 2e c0 2b c0 2c c0 ac c0 ad 13
    01 13 02 13 03 13 04 13 05 00 8c c0 aa c0 ab c0
    ab 00 8b 00 ae c0 a4 c0 a8 00 a8 00 8d 00 af c0
    a5 c0 a9 00 a9 00 8a 00 8f 00 90 c0 a6 00 aa 00
    91 00 b3 c0 a7 00 ab 00 8e c0 34 c0 35 c0 23 c0
    36 c0 38 c0 33 00 0f 00 3f 00 43 00 48 00 49 00
    4a 00 68 00 69 00 86 00 92 00 93 00 94 00 95 00
    98 00 ac 00 ad 00 b2 00 b6 00 b7 00 ba 00 bc 00
    be 00 c0 00 c2 00 c4 c0 02 c0 07 c0 0c c0 15 c0
    1d c0 20 c0 25 c0 26 c0 29 c0 2a c0 37 c0 3c c0
    3d c0 48 c0 49 c0 4a c0 4b c0 4c c0 4d c0 4e c0
    4f c0 50 c0 51 c0 52 c0 53 c0 54 c0 55 c0 5c c0
    5d c0 5e c0 5f c0 60 c0 61 c0 62 c0 63 c0 64 c0
    65 c0 66 c0 67 c0 68 c0 69 c0 6a c0 6b c0 6c c0
    6d c0 6e c0 6f c0 70 c0 71 c0 72 c0 73 c0 74 c0
    75 c0 76 c0 77 c0 78 c0 79 c0 7a c0 7b c0 7c c0
    7d c0 7e c0 7f c0 86 c0 87 c0 88 c0 89 c0 8a c0
    8b c0 8c c0 8d c0 8e c0 8f c0 90 c0 91 c0 92 c0
    93 c0 94 c0 95 c0 96 c0 97 c0 98 c0 99 c0 9a c0
    9b 00 2c 00 2d 00 2e 00 3b 00 47 00 b0 00 b1 00
    b4 00 b5 00 b8 00 b9 c0 01 c0 06 c0 0b c0 10 c0
    39 c0 3a c0 3b 00 0c 00 12 00 3e 00 40 00 42 00
    44 00 46 00 57 00 58 00 59 00 5a 00 6a 00 85 00
    87 00 89 00 97 00 99 00 9b 00 a4 00 bb 00 bd 00
    bf 00 c1 00 c3 00 c5 c0 16 c0 17 c0 18 c0 19 c0
    3e c0 3f c0 40 c0 41 c0 42 c0 43 c0 44 c0 45 c0
    46 c0 47 c0 56 c0 57 c0 58 c0 59 c0 5a c0 5b c0
    80 c0 81 c0 82 c0 83 c0 84 c0 85 00 81 00 83 ff
    85 ff 87 cc aa cc a9 cc a8 c0 b0 c0 b1 c0 b2 c0
    b3 c0 a0 c0 a1 c0 a2 c0 a3 c0 ae c0 af cc ab cc
    ac cc ad cc ae cc 12 cc 13 cc 14 cc 15 cc 16 cc
    17 cc 18 cc 19 00 00 01 00 00 8a 00 0b 00 02 01
    00 00 0a 00 3e 00 3c 00 0f 00 10 00 11 00 12 00
    13 00 14 00 15 00 16 00 17 00 18 00 19 00 01 00
    02 00 03 00 04 00 05 00 06 00 07 00 08 00 09 00
    0a 00 0b 00 0c 00 0d 00 0e 00 1d 00 1e 00 1a 00
    1b 00 1c 00 0d 00 08 00 06 04 01 04 03 08 04 00
    2b 00 03 02 03 04 00 33 00 26 00 24 00 1d 00 20
    b1 e8 23 6b 63 1e 19 d8 6b 28 a6 ff 4d 5f 4b 39
    d4 1e dd f4 7a b7 d3 a9 57 95 06 de c3 da 27 2a
    ff 01 00 01 00
>>> ??? [length 0005]
    16 03 03 00 5a
>>> TLS 1.3, Handshake [length 005a], ServerHello
    02 00 00 56 03 03 a6 2d 9a 6f f6 4a 62 6d df 03
    21 45 9f 9f f5 0a c9 4f c7 22 47 dc cd 3d 8e 50
    bb 89 79 79 e9 a0 00 13 01 00 00 2e 00 2b 00 02
    03 04 00 33 00 24 00 1d 00 20 ae 1a fa 17 62 f3
    3a c4 5c 77 85 f5 8a ab 0a 1d af c5 f6 a1 0c ca
    5e 8e bd 1a 06 ce dd a4 1d 02
>>> ??? [length 0005]
    14 03 03 00 01
>>> TLS 1.3, ChangeCipherSpec [length 0001]
    01
>>> ??? [length 0005]
    17 03 03 00 17
>>> TLS 1.3 [length 0001]
    16
>>> TLS 1.3, Handshake [length 0006], EncryptedExtensions
    08 00 00 02 00 00
>>> ??? [length 0005]
    17 03 03 00 42
>>> TLS 1.3 [length 0001]
    16
>>> TLS 1.3, Handshake [length 0031], CertificateRequest
    0d 00 00 2d 00 00 2a 00 0d 00 26 00 24 04 03 05
    03 06 03 08 07 08 08 08 09 08 0a 08 0b 08 04 08
    05 08 06 04 01 05 01 06 01 03 03 02 03 03 01 02
    01
>>> ??? [length 0005]
    17 03 03 06 24
>>> TLS 1.3 [length 0001]
    16
>>> TLS 1.3, Handshake [length 0613], Certificate
    0b 00 06 0f 00 00 06 0b 00 06 06 30 82 06 02 30
    82 03 ea a0 03 02 01 02 02 14 24 15 4f b7 d8 88
    5c c8 7e 6e 2b e7 6b 79 0b 36 a5 39 35 a4 30 0d
    06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 81 87
    31 0b 30 09 06 03 55 04 06 13 02 49 4e 31 0b 30
    09 06 03 55 04 08 0c 02 54 53 31 0c 30 0a 06 03
    55 04 07 0c 03 48 59 44 31 12 30 10 06 03 55 04
    0a 0c 09 50 61 72 69 6d 69 74 68 61 31 0c 30 0a
    06 03 55 04 0b 0c 03 45 6e 67 31 15 30 13 06 03
    55 04 03 0c 0c 70 61 72 69 6d 69 74 68 61 2e 69
    6f 31 24 30 22 06 09 2a 86 48 86 f7 0d 01 09 01
    16 15 63 6f 6e 74 61 63 74 40 70 61 72 69 6d 69
    74 68 61 2e 63 6f 6d 30 1e 17 0d 32 30 31 31 30
    32 31 33 30 34 31 34 5a 17 0d 33 30 31 30 33 31
    31 33 30 34 31 34 5a 30 81 87 31 0b 30 09 06 03
    55 04 06 13 02 49 4e 31 0b 30 09 06 03 55 04 08
    0c 02 54 53 31 0c 30 0a 06 03 55 04 07 0c 03 48
    59 44 31 12 30 10 06 03 55 04 0a 0c 09 50 61 72
    69 6d 69 74 68 61 31 0c 30 0a 06 03 55 04 0b 0c
    03 45 6e 67 31 15 30 13 06 03 55 04 03 0c 0c 70
    61 72 69 6d 69 74 68 61 2e 69 6f 31 24 30 22 06
    09 2a 86 48 86 f7 0d 01 09 01 16 15 63 6f 6e 74
    61 63 74 40 70 61 72 69 6d 69 74 68 61 2e 63 6f
    6d 30 82 02 22 30 0d 06 09 2a 86 48 86 f7 0d 01
    01 01 05 00 03 82 02 0f 00 30 82 02 0a 02 82 02
    01 00 df 56 32 70 e8 5d e2 b8 eb 61 12 9c c2 58
    3f 68 d8 22 c2 79 c2 9d cf d7 a5 f0 e0 62 f6 ac
    23 88 ea cf 6f b2 0e df 33 23 81 f8 cb 36 78 3f
    04 1c 33 f5 ce c3 a5 b1 8a 6f da d0 d7 94 76 9a
    5f db 24 a9 3f 08 77 8f 60 5b ad 31 28 17 42 6e
    0f f3 d4 a4 87 b4 07 b3 4a 5d ce a6 ee a2 98 2b
    3f 0a 8c 8a 3e 8c 85 e9 5c 94 8a 51 d3 73 fa 75
    4d 7e b9 16 c6 ac a6 a8 6a 20 66 cf ef d2 d8 46
    1f 22 03 88 ef 88 c4 55 39 e3 90 7a b0 98 a6 34
    53 af e2 19 57 5b 8d b6 20 ae 9e 28 64 56 d9 7f
    24 2f b2 51 aa de eb 55 c2 b9 18 64 1b 8f 5b 7e
    87 0b d0 4e ee f9 c1 62 5a 84 4d 83 ac 64 a5 cf
    cb 6a fc a7 18 6d a9 44 8f 57 72 91 0b c2 a9 37
    28 a5 d7 ae a6 9e bf 81 34 c1 1a 0f b6 20 5a 67
    1c de c6 53 84 63 7b 7e dc d5 ca b6 14 5d d7 8c
    0f 5d f6 1e 5e 03 fb 48 b8 ff ea a6 ca 26 2e f5
    89 9c be cb 41 57 c0 56 1d 0e 84 cc 36 8c 8f 35
    1f 94 b5 7b 03 7a a4 8e 3f 02 65 7c 49 fa 07 88
    1e 7e e6 41 51 3b 5c 3b b6 27 d8 1f 00 52 fe 33
    ec 33 7f 29 78 e4 f9 52 7c cd cc de 9a 49 92 a0
    b8 a7 3a a1 6f 5d dc 75 1a ab aa b6 53 60 98 27
    cc a9 ca cf e6 8e 46 b5 e1 44 49 cb eb 7d 9d c1
    64 49 30 40 22 0a a2 8a 4b e8 ac 82 b2 90 18 b5
    94 de e2 d3 b0 c1 ee f9 14 49 11 b3 6b ec 73 4d
    9b a0 10 fc 8b 14 b7 98 77 54 c6 27 c5 65 2d 8c
    e6 15 45 bd bb 11 53 95 39 d5 f9 01 97 0a 88 c2
    6e e9 3b d0 d7 da be 9f dc 60 ff f0 59 c0 89 85
    42 a0 4f 60 19 07 46 ea cd 4f b3 c2 da 16 83 20
    f1 95 22 df c4 13 db 63 f0 29 da 89 10 63 b5 18
    4f 3c fd f4 d1 9e 96 6a 78 70 57 5d 93 3b 9e 34
    c3 6b 21 86 b3 33 14 62 78 fc a4 ed 38 97 d0 2a
    eb 0c 87 20 f4 44 0a 44 17 12 ca 52 87 14 07 a6
    c2 a9 02 03 01 00 01 a3 64 30 62 30 1d 06 03 55
    1d 0e 04 16 04 14 34 c6 e6 e8 af d0 bf 0f 36 95
    06 b9 b1 39 57 cf e4 a2 28 69 30 1f 06 03 55 1d
    23 04 18 30 16 80 14 34 c6 e6 e8 af d0 bf 0f 36
    95 06 b9 b1 39 57 cf e4 a2 28 69 30 0f 06 03 55
    1d 13 01 01 ff 04 05 30 03 01 01 ff 30 0f 06 03
    55 1d 11 04 08 30 06 87 04 7f 00 00 01 30 0d 06
    09 2a 86 48 86 f7 0d 01 01 0b 05 00 03 82 02 01
    00 88 95 f4 75 cc 70 c4 10 1d cb d2 d0 35 78 c0
    f2 9d 0e 5b 79 a2 6a a0 87 6a 02 35 82 1e dc da
    ba 31 96 19 fe c2 93 ae 1b 98 57 07 22 d3 35 e4
    f5 2a 5d ed 86 5f d3 c1 d6 61 a2 dc f0 98 1b 41
    6a 79 62 38 fc 7e 0a 7f f9 b4 83 48 e1 89 7a 24
    cd a7 89 82 27 f5 19 07 c9 fd 36 9c 64 d8 e7 c5
    e0 d1 12 5d 10 84 24 4d e9 a8 e8 4f 78 19 e7 c0
    9e a9 9c 4e e1 05 6e bf c5 e1 f1 09 c4 50 8f 4a
    c7 54 72 f5 26 18 b6 b4 e7 0b 03 6a 4a e1 cc 29
    e9 df 6a c1 c5 08 7a 2b 49 44 4c 75 df 79 b8 1c
    e6 f7 a3 e2 59 d0 a6 d2 88 fa 97 61 50 79 ad f8
    2b f8 b7 63 62 17 5f 9d cc 23 01 d5 6d 05 de ee
    aa 24 a7 42 85 e8 26 23 c4 d0 82 c7 33 26 30 f5
    76 c6 cc cb 27 9d 51 ef 77 fd 5e 64 67 de 79 fc
    5f a9 67 a2 75 db 3f 1c 19 3c 69 5d 11 20 d9 f9
    97 b6 ad 1a 51 ee 19 f4 93 4f 13 57 47 f3 50 df
    77 99 d9 a2 aa b6 47 97 76 b4 8b 7b 5a e8 87 6a
    db 84 ac d9 53 f6 95 09 90 5e 33 26 03 22 12 38
    38 9b 76 2f f7 a2 f7 c0 4d 22 75 13 31 d8 eb fb
    cd 27 4b d8 7b 91 9e 25 39 e4 80 3c 7f 25 af cf
    76 a7 da 50 bf 86 75 40 9f 3f 12 aa 4f 4c 57 25
    a7 7a f9 70 47 25 4f 80 a0 05 72 64 1a bc b4 dc
    07 8f e0 0a 6c 91 4b 0f b2 da e4 85 ec f0 3c 7f
    24 ac 36 0f 65 75 bf ee 3b 95 f6 a1 ce 45 44 51
    19 d5 91 ae cd 44 08 79 bb 30 98 a3 58 e7 bc bc
    af dd 75 38 fd 62 4a 55 43 e5 e0 4f 29 38 2c df
    21 45 87 10 66 68 01 c8 74 7c 88 ac f9 81 15 05
    1e 33 b5 f8 3b 70 96 63 cb 9f 3d 5e 07 8e 97 a9
    a3 29 32 b6 e9 80 a6 d1 e0 5e 46 b7 7d 5c ab 19
    89 83 4f ca c3 0b 6b ad 7b 85 ba 89 8c c8 ae c3
    04 ac cb 02 77 68 c0 a8 25 45 80 d0 4e ae 99 eb
    1b 38 42 57 37 d4 06 61 00 15 f8 d3 94 08 9c 0b
    db 00 00
>>> ??? [length 0005]
    17 03 03 02 19
>>> TLS 1.3 [length 0001]
    16
>>> TLS 1.3, Handshake [length 0208], CertificateVerify
    0f 00 02 04 08 04 02 00 0f a1 d6 74 6a 53 8d 98
    6f cb 5d 62 5e bc 67 ec b9 ae 86 b5 8e ed 1b 53
    b5 9e 99 aa 21 2b a6 8c 9a dd 1f a4 03 13 55 54
    62 e6 dd ee 10 49 bd 70 da 36 2a 8f a3 0e 12 f0
    89 58 1d 6c 0e f9 55 bf e2 d6 08 d7 40 ca 85 a5
    6d 03 f6 88 80 3c 13 14 ea 9b cc e0 c3 f5 17 ec
    dc 3f 1a 11 70 95 95 6e 9e 6d 1a fc b2 e7 82 36
    36 b5 ef 2f f2 57 5c 1f f5 c7 44 8d db 51 9d cd
    69 cd 3c 2b 08 17 4b c7 8a 41 f8 0a 48 79 19 af
    48 5d 8d 19 49 79 26 42 25 d5 b9 9c 6d a0 a2 91
    62 37 ad f9 af 61 58 94 0b 70 a5 18 39 f3 8b de
    64 d8 c8 cc de 9a 6c bf f7 42 35 7a cf 04 48 f6
    a6 9e 4d 74 86 e8 30 7f c7 87 db ef dd 30 66 93
    1a 57 9b ab 5e 95 6a 6e 58 e4 24 49 32 18 ae a3
    a2 48 60 02 bf 79 e4 33 0f 30 49 93 14 27 48 bb
    c2 5b f7 6d 16 81 7b 4f 28 6f df 6d 51 81 db 74
    f0 cd 0b a0 7f fc 7a 87 d5 27 bb dc 61 a9 0c 8a
    17 a7 eb 0f 78 73 49 37 ea 79 fe d6 53 7c a4 95
    5b e3 a3 ba 6e ed 56 9e ce 6a 78 f1 a2 d0 20 f5
    30 81 01 87 91 6a 8e a9 51 a0 70 af 7d fe 55 1c
    6f 1a fb f9 f8 30 98 ce 5b ad 03 72 b7 f1 76 75
    21 4a 71 51 d6 a4 33 67 83 c5 4d 0e fb 92 89 43
    56 b6 20 15 cc 30 d7 a5 cc b5 38 0f 8e 50 8d 3a
    74 f7 68 d2 15 88 4c af 2a 50 ed 87 dd 0c 00 f0
    d7 b3 f1 f1 51 66 86 2f 58 23 9d bf f7 f1 a9 6c
    8c 24 58 b0 9c 6d 28 94 0a 80 d5 4d 24 84 24 61
    33 32 70 13 87 66 8d a3 08 5c b1 75 b1 19 bb 7a
    15 f0 ac e0 bd 0e bb 33 68 af d0 81 49 3f 51 54
    5d 62 d1 fa aa c0 44 fe 98 16 6c 3f a1 c4 31 53
    2d 76 52 11 59 0d d7 66 e9 fd 06 28 82 c4 b9 89
    40 04 a1 13 ce 73 d1 81 72 7f 6d 52 6f bc e7 88
    9f 04 f2 9d e3 c4 f9 c1 f2 78 6d 70 3b d8 ca 7b
    28 c2 47 f0 92 9c 2f 37
>>> ??? [length 0005]
    17 03 03 00 35
>>> TLS 1.3 [length 0001]
    16
>>> TLS 1.3, Handshake [length 0024], Finished
    14 00 00 20 35 04 a2 56 9d bc 12 03 16 7a bb 10
    a3 f2 e8 ef 7e 72 2d 60 bb 96 ab 60 d8 84 64 7a
    b6 20 37 ff
<<< ??? [length 0005]
    14 03 03 00 01
<<< ??? [length 0005]
    16 03 03 03 07
>>> ??? [length 0005]
    17 03 03 00 13
>>> TLS 1.3 [length 0001]
    15
>>> TLS 1.3, Alert [length 0002], fatal unexpected_message
    02 0a
ERROR
4463287808:error:1408F1BB:SSL routines:ssl3_get_record:bad record type:ssl/record/ssl3_record.c:350:
shutting down SSL
CONNECTION CLOSED
```

Able do handshake but getting Alert Fatal and unexpected_message
Attached tlsattacker debug log. 
[tlsattacker_debug.log](https://github.com/tls-attacker/TLS-Attacker/files/6298042/tlsattacker_debug.log)

**Comment by ic0ns** [comment] 2021-04-12 15:58
You are using 1024bit certificate file with a 2048bit key - this should never work.

**Comment by ic0ns** [comment] 2021-04-12 16:03
Aslo you are currently only showing what Openssl thinks of this connection. Can you add more information on what TLS-Attacker thinks happened in this session? Like, debug output or anything. It would also be helpful to see the full Config you created. TLS-Attacker can be kind of a footgun - as it does exactly what you tell it to do and it's easy to mess up the config - especially for TLS 1.3.

**Comment by skommula96** [comment] 2021-04-12 16:20
Sorry typo in file changed to rsa2048.crt
Attached debug.log
workflow trace type**.FULL**

```
tls13Init.setClientAuthentication(true);
tls13Init.setClientAutoSelectCertificate(false);
Certificate readCertificate = PemUtil.readCertificate(new FileInputStream(new File("src/main/resources/rsa2048.crt")));
PrivateKey privateKey = PemUtil.readPrivateKey(new FileInputStream(new File("src/main/resources/rsa2048.key")));
tls13Init.setClientDefaultExplicitCertificateKeyPair(new CertificateKeyPair(readCertificate, privateKey));
State state = TLS13Execute.execute(tls13Init.getConf(), classWorkflowTraceType, alert);
AssertionCheck.checkHandshakeMessages(state);
```
[debugger.log](https://github.com/tls-attacker/TLS-Attacker/files/6298251/debugger.log)

**Comment by ic0ns** [comment] 2021-04-12 16:32
Ok it seems like the CertificateRequestMessage could not be parsed correctly. I think I remember this is an issue in the current public version of TLS-Attacker which is already fixed in our development version by @mmaehren . We plan to release the new version mid may.

**Comment by ic0ns** [comment] 2021-04-12 16:33
I think this only affects TLS 1.3

**Comment by skommula96** [comment] 2021-04-12 17:26
@mmaehren can you please help the CertificateRequestMessage patch.
So I can apply and test it

Thanks in advance

**Comment by ic0ns** [comment] 2021-04-28 08:25
You can find the dev version here: https://github.com/tls-attacker/TLS-Attacker/tree/dev

**Comment by skommula96** [comment] 2021-05-02 11:34
Can you please point out the exact commit. So many commits in  dev branch. @ic0ns 
Thanks in advance

**Comment by ic0ns** [comment] 2021-09-09 16:36
It should be fixed now in the current master branch

**Closed by ic0ns** 2021-09-09 16:36 UTC
